# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: livekit_internal.proto

require 'google/protobuf'

require 'livekit_rtc_pb'
require 'livekit_room_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("livekit_internal.proto", :syntax => :proto3) do
    add_message "livekit.Node" do
      optional :id, :string, 1
      optional :ip, :string, 2
      optional :num_cpus, :uint32, 3
      optional :stats, :message, 4, "livekit.NodeStats"
    end
    add_message "livekit.NodeStats" do
      optional :started_at, :int64, 1
      optional :updated_at, :int64, 2
      optional :num_rooms, :uint32, 3
      optional :num_clients, :uint32, 4
      optional :num_tracks_in, :uint32, 5
      optional :num_tracks_out, :uint32, 6
    end
    add_message "livekit.RTCNodeMessage" do
      optional :participant_key, :string, 1
      oneof :message do
        optional :start_session, :message, 2, "livekit.StartSession"
        optional :request, :message, 3, "livekit.SignalRequest"
        optional :remove_participant, :message, 4, "livekit.RoomParticipantIdentity"
        optional :mute_track, :message, 5, "livekit.MuteRoomTrackRequest"
        optional :update_participant, :message, 6, "livekit.UpdateParticipantRequest"
        optional :delete_room, :message, 7, "livekit.DeleteRoomRequest"
        optional :update_subscriptions, :message, 8, "livekit.UpdateSubscriptionsRequest"
      end
    end
    add_message "livekit.SignalNodeMessage" do
      optional :connection_id, :string, 1
      oneof :message do
        optional :response, :message, 2, "livekit.SignalResponse"
        optional :end_session, :message, 3, "livekit.EndSession"
      end
    end
    add_message "livekit.StartSession" do
      optional :room_name, :string, 1
      optional :identity, :string, 2
      optional :connection_id, :string, 3
      optional :reconnect, :bool, 4
      optional :metadata, :string, 5
      optional :permission, :message, 6, "livekit.ParticipantPermission"
      optional :protocol_version, :int32, 7
      optional :use_plan_b, :bool, 8
      optional :auto_subscribe, :bool, 9
      optional :hidden, :bool, 10
    end
    add_message "livekit.EndSession" do
    end
    add_message "livekit.RemoveParticipant" do
      optional :participant_id, :string, 1
    end
  end
end

module Livekit
  Node = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("livekit.Node").msgclass
  NodeStats = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("livekit.NodeStats").msgclass
  RTCNodeMessage = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("livekit.RTCNodeMessage").msgclass
  SignalNodeMessage = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("livekit.SignalNodeMessage").msgclass
  StartSession = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("livekit.StartSession").msgclass
  EndSession = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("livekit.EndSession").msgclass
  RemoveParticipant = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("livekit.RemoveParticipant").msgclass
end
