# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: livekit_recording.proto

require 'google/protobuf'

require 'google/protobuf/empty_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("livekit_recording.proto", :syntax => :proto3) do
    add_message "livekit.StartRecordingRequest" do
      optional :options, :message, 5, "livekit.RecordingOptions"
      oneof :input do
        optional :url, :string, 1
        optional :template, :message, 2, "livekit.RecordingTemplate"
      end
      oneof :output do
        optional :rtmp, :message, 3, "livekit.RtmpOutput"
        optional :filepath, :string, 4
      end
    end
    add_message "livekit.RecordingTemplate" do
      optional :layout, :string, 1
      optional :room_name, :string, 2
      optional :base_url, :string, 3
    end
    add_message "livekit.RtmpOutput" do
      repeated :urls, :string, 1
    end
    add_message "livekit.RecordingOptions" do
      optional :preset, :enum, 1, "livekit.RecordingPreset"
      optional :width, :int32, 2
      optional :height, :int32, 3
      optional :depth, :int32, 4
      optional :framerate, :int32, 5
      optional :audio_bitrate, :int32, 6
      optional :audio_frequency, :int32, 7
      optional :video_bitrate, :int32, 8
      optional :profile, :string, 9
    end
    add_message "livekit.StartRecordingResponse" do
      optional :recording_id, :string, 1
    end
    add_message "livekit.AddOutputRequest" do
      optional :recording_id, :string, 1
      optional :rtmp_url, :string, 2
    end
    add_message "livekit.RemoveOutputRequest" do
      optional :recording_id, :string, 1
      optional :rtmp_url, :string, 2
    end
    add_message "livekit.EndRecordingRequest" do
      optional :recording_id, :string, 1
    end
    add_message "livekit.RecordingInfo" do
      optional :id, :string, 1
      optional :room_name, :string, 2
      optional :active, :bool, 3
      optional :error, :string, 4
      optional :file, :message, 5, "livekit.FileResult"
      repeated :rtmp, :message, 6, "livekit.RtmpResult"
    end
    add_message "livekit.FileResult" do
      optional :download_url, :string, 1
      optional :duration, :int64, 2
    end
    add_message "livekit.RtmpResult" do
      optional :stream_url, :string, 1
      optional :duration, :int64, 2
    end
    add_enum "livekit.RecordingPreset" do
      value :NONE, 0
      value :HD_30, 1
      value :HD_60, 2
      value :FULL_HD_30, 3
      value :FULL_HD_60, 4
    end
  end
end

module LiveKit
  module Proto
    StartRecordingRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("livekit.StartRecordingRequest").msgclass
    RecordingTemplate = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("livekit.RecordingTemplate").msgclass
    RtmpOutput = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("livekit.RtmpOutput").msgclass
    RecordingOptions = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("livekit.RecordingOptions").msgclass
    StartRecordingResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("livekit.StartRecordingResponse").msgclass
    AddOutputRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("livekit.AddOutputRequest").msgclass
    RemoveOutputRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("livekit.RemoveOutputRequest").msgclass
    EndRecordingRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("livekit.EndRecordingRequest").msgclass
    RecordingInfo = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("livekit.RecordingInfo").msgclass
    FileResult = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("livekit.FileResult").msgclass
    RtmpResult = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("livekit.RtmpResult").msgclass
    RecordingPreset = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("livekit.RecordingPreset").enummodule
  end
end
