# Code generated by protoc-gen-twirp_ruby 1.10.0, DO NOT EDIT.
require 'twirp'
require_relative 'livekit_egress_pb.rb'

module LiveKit
  module Proto
    class EgressService < ::Twirp::Service
      package 'livekit'
      service 'Egress'
      rpc :StartRoomCompositeEgress, RoomCompositeEgressRequest, EgressInfo, :ruby_method => :start_room_composite_egress
      rpc :StartWebEgress, WebEgressRequest, EgressInfo, :ruby_method => :start_web_egress
      rpc :StartParticipantEgress, ParticipantEgressRequest, EgressInfo, :ruby_method => :start_participant_egress
      rpc :StartTrackCompositeEgress, TrackCompositeEgressRequest, EgressInfo, :ruby_method => :start_track_composite_egress
      rpc :StartTrackEgress, TrackEgressRequest, EgressInfo, :ruby_method => :start_track_egress
      rpc :UpdateLayout, UpdateLayoutRequest, EgressInfo, :ruby_method => :update_layout
      rpc :UpdateStream, UpdateStreamRequest, EgressInfo, :ruby_method => :update_stream
      rpc :UpdateOutputs, UpdateOutputsRequest, EgressInfo, :ruby_method => :update_outputs
      rpc :ListEgress, ListEgressRequest, ListEgressResponse, :ruby_method => :list_egress
      rpc :StopEgress, StopEgressRequest, EgressInfo, :ruby_method => :stop_egress
    end

    class EgressClient < ::Twirp::Client
      client_for EgressService
    end
  end
end
