# Code generated by protoc-gen-twirp_ruby 1.0.0, DO NOT EDIT.
# source: livekit_webhook.proto

require "json"
require "net/https"
require "google/protobuf"

module Livekit
  class Error < StandardError; end

  class ServiceError < Error
    attr_reader :code
    attr_reader :meta
    attr_reader :message

    def initialize(response)
      error = JSON.parse(response.body)

      @code    = error["code"]
      @meta    = error["meta"] || {}
      @message = error["msg"]
    end
  end

  WebhookEvent ||= ::Google::Protobuf::DescriptorPool.generated_pool.lookup("livekit.WebhookEvent").msgclass
  

  
end
