# Code generated by protoc-gen-twirp_ruby 1.14.1, DO NOT EDIT.
require 'twirp'
require_relative 'livekit_connector_pb.rb'

module LiveKit
  module Proto
    class ConnectorService < ::Twirp::Service
      package 'livekit'
      service 'Connector'
      rpc :DialWhatsAppCall, DialWhatsAppCallRequest, DialWhatsAppCallResponse, :ruby_method => :dial_whats_app_call
      rpc :DisconnectWhatsAppCall, DisconnectWhatsAppCallRequest, DisconnectWhatsAppCallResponse, :ruby_method => :disconnect_whats_app_call
      rpc :ConnectWhatsAppCall, ConnectWhatsAppCallRequest, ConnectWhatsAppCallResponse, :ruby_method => :connect_whats_app_call
      rpc :AcceptWhatsAppCall, AcceptWhatsAppCallRequest, AcceptWhatsAppCallResponse, :ruby_method => :accept_whats_app_call
      rpc :ConnectTwilioCall, ConnectTwilioCallRequest, ConnectTwilioCallResponse, :ruby_method => :connect_twilio_call
    end

    class ConnectorClient < ::Twirp::Client
      client_for ConnectorService
    end
  end
end
