# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: livekit_recording.proto

require 'google/protobuf'

require 'livekit_models_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("livekit_recording.proto", :syntax => :proto3) do
    add_message "livekit.StartRecordingRequest" do
      optional :options, :message, 6, "livekit.RecordingOptions"
      oneof :input do
        optional :url, :string, 1
        optional :template, :message, 2, "livekit.RecordingTemplate"
      end
      oneof :output do
        optional :file, :string, 3
        optional :s3, :message, 4, "livekit.RecordingS3Output"
        optional :rtmp, :string, 5
      end
    end
    add_message "livekit.EndRecordingRequest" do
      optional :recording_id, :string, 1
    end
    add_message "livekit.RecordingResponse" do
      optional :recording_id, :string, 1
    end
  end
end

module Livekit
  module Proto
    StartRecordingRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("livekit.StartRecordingRequest").msgclass
    EndRecordingRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("livekit.EndRecordingRequest").msgclass
    RecordingResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("livekit.RecordingResponse").msgclass
  end
end
