# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: livekit_webhook.proto

require 'livekit_models_pb'
require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("livekit_webhook.proto", :syntax => :proto3) do
    add_message "livekit.WebhookEvent" do
      optional :event, :string, 1
      optional :room, :message, 2, "livekit.Room"
      optional :participant, :message, 3, "livekit.ParticipantInfo"
      optional :recording_result, :message, 4, "livekit.RecordingResult"
    end
    add_message "livekit.RecordingResult" do
      optional :id, :string, 1
      optional :error, :string, 2
      optional :duration, :int64, 3
      optional :download_url, :string, 4
    end
  end
end

module Livekit
  module Proto
    WebhookEvent = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("livekit.WebhookEvent").msgclass
    RecordingResult = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("livekit.RecordingResult").msgclass
  end
end
