# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: livekit_rtc.proto

require 'google/protobuf'

require 'livekit_models_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("livekit_rtc.proto", :syntax => :proto3) do
    add_message "livekit.SignalRequest" do
      oneof :message do
        optional :offer, :message, 1, "livekit.SessionDescription"
        optional :answer, :message, 2, "livekit.SessionDescription"
        optional :trickle, :message, 3, "livekit.TrickleRequest"
        optional :add_track, :message, 4, "livekit.AddTrackRequest"
        optional :mute, :message, 5, "livekit.MuteTrackRequest"
        optional :subscription, :message, 6, "livekit.UpdateSubscription"
        optional :track_setting, :message, 7, "livekit.UpdateTrackSettings"
        optional :leave, :message, 8, "livekit.LeaveRequest"
        optional :simulcast, :message, 9, "livekit.SetSimulcastLayers"
      end
    end
    add_message "livekit.SignalResponse" do
      oneof :message do
        optional :join, :message, 1, "livekit.JoinResponse"
        optional :answer, :message, 2, "livekit.SessionDescription"
        optional :offer, :message, 3, "livekit.SessionDescription"
        optional :trickle, :message, 4, "livekit.TrickleRequest"
        optional :update, :message, 5, "livekit.ParticipantUpdate"
        optional :track_published, :message, 6, "livekit.TrackPublishedResponse"
        optional :speaker, :message, 7, "livekit.ActiveSpeakerUpdate"
        optional :leave, :message, 8, "livekit.LeaveRequest"
      end
    end
    add_message "livekit.AddTrackRequest" do
      optional :cid, :string, 1
      optional :name, :string, 2
      optional :type, :enum, 3, "livekit.TrackType"
      optional :width, :uint32, 4
      optional :height, :uint32, 5
      optional :muted, :bool, 6
    end
    add_message "livekit.TrickleRequest" do
      optional :candidateInit, :string, 1
      optional :target, :enum, 2, "livekit.SignalTarget"
    end
    add_message "livekit.MuteTrackRequest" do
      optional :sid, :string, 1
      optional :muted, :bool, 2
    end
    add_message "livekit.SetSimulcastLayers" do
      optional :track_sid, :string, 1
      repeated :layers, :enum, 2, "livekit.VideoQuality"
    end
    add_message "livekit.JoinResponse" do
      optional :room, :message, 1, "livekit.Room"
      optional :participant, :message, 2, "livekit.ParticipantInfo"
      repeated :other_participants, :message, 3, "livekit.ParticipantInfo"
      optional :server_version, :string, 4
      repeated :ice_servers, :message, 5, "livekit.ICEServer"
    end
    add_message "livekit.TrackPublishedResponse" do
      optional :cid, :string, 1
      optional :track, :message, 2, "livekit.TrackInfo"
    end
    add_message "livekit.SessionDescription" do
      optional :type, :string, 1
      optional :sdp, :string, 2
    end
    add_message "livekit.ParticipantUpdate" do
      repeated :participants, :message, 1, "livekit.ParticipantInfo"
    end
    add_message "livekit.ActiveSpeakerUpdate" do
      repeated :speakers, :message, 1, "livekit.SpeakerInfo"
    end
    add_message "livekit.SpeakerInfo" do
      optional :sid, :string, 1
      optional :level, :float, 2
      optional :active, :bool, 3
    end
    add_message "livekit.UpdateSubscription" do
      repeated :track_sids, :string, 1
      optional :subscribe, :bool, 2
    end
    add_message "livekit.UpdateTrackSettings" do
      repeated :track_sids, :string, 1
      optional :disabled, :bool, 3
      optional :quality, :enum, 4, "livekit.VideoQuality"
    end
    add_message "livekit.LeaveRequest" do
      optional :can_reconnect, :bool, 1
    end
    add_message "livekit.ICEServer" do
      repeated :urls, :string, 1
      optional :username, :string, 2
      optional :credential, :string, 3
    end
    add_message "livekit.DataPacket" do
      optional :kind, :enum, 1, "livekit.DataPacket.Kind"
      oneof :value do
        optional :user, :message, 2, "livekit.UserPacket"
        optional :speaker, :message, 3, "livekit.ActiveSpeakerUpdate"
      end
    end
    add_enum "livekit.DataPacket.Kind" do
      value :RELIABLE, 0
      value :LOSSY, 1
    end
    add_message "livekit.UserPacket" do
      optional :participant_sid, :string, 1
      optional :payload, :bytes, 2
      repeated :destination_sids, :string, 3
    end
    add_enum "livekit.SignalTarget" do
      value :PUBLISHER, 0
      value :SUBSCRIBER, 1
    end
    add_enum "livekit.VideoQuality" do
      value :LOW, 0
      value :MEDIUM, 1
      value :HIGH, 2
    end
  end
end

module Livekit
  module Proto
    SignalRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("livekit.SignalRequest").msgclass
    SignalResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("livekit.SignalResponse").msgclass
    AddTrackRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("livekit.AddTrackRequest").msgclass
    TrickleRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("livekit.TrickleRequest").msgclass
    MuteTrackRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("livekit.MuteTrackRequest").msgclass
    SetSimulcastLayers = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("livekit.SetSimulcastLayers").msgclass
    JoinResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("livekit.JoinResponse").msgclass
    TrackPublishedResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("livekit.TrackPublishedResponse").msgclass
    SessionDescription = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("livekit.SessionDescription").msgclass
    ParticipantUpdate = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("livekit.ParticipantUpdate").msgclass
    ActiveSpeakerUpdate = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("livekit.ActiveSpeakerUpdate").msgclass
    SpeakerInfo = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("livekit.SpeakerInfo").msgclass
    UpdateSubscription = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("livekit.UpdateSubscription").msgclass
    UpdateTrackSettings = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("livekit.UpdateTrackSettings").msgclass
    LeaveRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("livekit.LeaveRequest").msgclass
    ICEServer = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("livekit.ICEServer").msgclass
    DataPacket = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("livekit.DataPacket").msgclass
    DataPacket::Kind = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("livekit.DataPacket.Kind").enummodule
    UserPacket = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("livekit.UserPacket").msgclass
    SignalTarget = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("livekit.SignalTarget").enummodule
    VideoQuality = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("livekit.VideoQuality").enummodule
  end
end
