# frozen_string_literal: true

# Generated by the protoc-gen-twirp_ruby gem v1.2.0. DO NOT EDIT!
# source: livekit_ingress.proto

require "twirp"
require_relative "livekit_ingress_pb"

module LiveKit
  module Proto
    class IngressService < ::Twirp::Service
      package "livekit"
      service "Ingress"
      rpc :CreateIngress, CreateIngressRequest, IngressInfo, ruby_method: :create_ingress
      rpc :UpdateIngress, UpdateIngressRequest, IngressInfo, ruby_method: :update_ingress
      rpc :ListIngress, ListIngressRequest, ListIngressResponse, ruby_method: :list_ingress
      rpc :DeleteIngress, DeleteIngressRequest, IngressInfo, ruby_method: :delete_ingress
    end

    class IngressClient < ::Twirp::Client
      client_for IngressService
    end
  end
end
