# Code generated by protoc-gen-twirp_ruby 1.0.0, DO NOT EDIT.
# source: livekit_models.proto

require "json"
require "net/https"
require "google/protobuf"

module Livekit
  class Error < StandardError; end

  class ServiceError < Error
    attr_reader :code
    attr_reader :meta
    attr_reader :message

    def initialize(response)
      error = JSON.parse(response.body)

      @code    = error["code"]
      @meta    = error["meta"] || {}
      @message = error["msg"]
    end
  end

  Room ||= ::Google::Protobuf::DescriptorPool.generated_pool.lookup("livekit.Room").msgclass
  Codec ||= ::Google::Protobuf::DescriptorPool.generated_pool.lookup("livekit.Codec").msgclass
  ParticipantPermission ||= ::Google::Protobuf::DescriptorPool.generated_pool.lookup("livekit.ParticipantPermission").msgclass
  ParticipantInfo ||= ::Google::Protobuf::DescriptorPool.generated_pool.lookup("livekit.ParticipantInfo").msgclass
  SimulcastCodecInfo ||= ::Google::Protobuf::DescriptorPool.generated_pool.lookup("livekit.SimulcastCodecInfo").msgclass
  TrackInfo ||= ::Google::Protobuf::DescriptorPool.generated_pool.lookup("livekit.TrackInfo").msgclass
  VideoLayer ||= ::Google::Protobuf::DescriptorPool.generated_pool.lookup("livekit.VideoLayer").msgclass
  DataPacket ||= ::Google::Protobuf::DescriptorPool.generated_pool.lookup("livekit.DataPacket").msgclass
  ActiveSpeakerUpdate ||= ::Google::Protobuf::DescriptorPool.generated_pool.lookup("livekit.ActiveSpeakerUpdate").msgclass
  SpeakerInfo ||= ::Google::Protobuf::DescriptorPool.generated_pool.lookup("livekit.SpeakerInfo").msgclass
  UserPacket ||= ::Google::Protobuf::DescriptorPool.generated_pool.lookup("livekit.UserPacket").msgclass
  ParticipantTracks ||= ::Google::Protobuf::DescriptorPool.generated_pool.lookup("livekit.ParticipantTracks").msgclass
  ServerInfo ||= ::Google::Protobuf::DescriptorPool.generated_pool.lookup("livekit.ServerInfo").msgclass
  ClientInfo ||= ::Google::Protobuf::DescriptorPool.generated_pool.lookup("livekit.ClientInfo").msgclass
  ClientConfiguration ||= ::Google::Protobuf::DescriptorPool.generated_pool.lookup("livekit.ClientConfiguration").msgclass
  VideoConfiguration ||= ::Google::Protobuf::DescriptorPool.generated_pool.lookup("livekit.VideoConfiguration").msgclass
  DisabledCodecs ||= ::Google::Protobuf::DescriptorPool.generated_pool.lookup("livekit.DisabledCodecs").msgclass
  RTPStats ||= ::Google::Protobuf::DescriptorPool.generated_pool.lookup("livekit.RTPStats").msgclass
  TimedVersion ||= ::Google::Protobuf::DescriptorPool.generated_pool.lookup("livekit.TimedVersion").msgclass
  

  
end
