# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: livekit_ingress.proto

require 'google/protobuf'

require 'livekit_models_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("livekit_ingress.proto", :syntax => :proto3) do
    add_message "livekit.CreateIngressRequest" do
      optional :input_type, :enum, 1, "livekit.IngressInput"
      optional :name, :string, 2
      optional :room_name, :string, 3
      optional :participant_identity, :string, 4
      optional :participant_name, :string, 5
      optional :audio, :message, 6, "livekit.IngressAudioOptions"
      optional :video, :message, 7, "livekit.IngressVideoOptions"
    end
    add_message "livekit.IngressAudioOptions" do
      optional :name, :string, 1
      optional :source, :enum, 2, "livekit.TrackSource"
      optional :audio_codec, :enum, 7, "livekit.AudioCodec"
      optional :bitrate, :uint32, 4
      optional :disable_dtx, :bool, 5
      optional :channels, :uint32, 6
    end
    add_message "livekit.IngressVideoOptions" do
      optional :name, :string, 1
      optional :source, :enum, 2, "livekit.TrackSource"
      optional :video_codec, :enum, 5, "livekit.VideoCodec"
      repeated :layers, :message, 4, "livekit.VideoLayer"
    end
    add_message "livekit.IngressInfo" do
      optional :ingress_id, :string, 1
      optional :name, :string, 2
      optional :stream_key, :string, 3
      optional :url, :string, 4
      optional :input_type, :enum, 5, "livekit.IngressInput"
      optional :audio, :message, 6, "livekit.IngressAudioOptions"
      optional :video, :message, 7, "livekit.IngressVideoOptions"
      optional :room_name, :string, 8
      optional :participant_identity, :string, 9
      optional :participant_name, :string, 10
      optional :reusable, :bool, 11
      optional :state, :message, 12, "livekit.IngressState"
    end
    add_message "livekit.IngressState" do
      optional :status, :enum, 1, "livekit.IngressState.Status"
      optional :error, :string, 2
      optional :video, :message, 3, "livekit.InputVideoState"
      optional :audio, :message, 4, "livekit.InputAudioState"
      optional :room_id, :string, 5
      optional :started_at, :int64, 7
      optional :ended_at, :int64, 8
      repeated :tracks, :message, 6, "livekit.TrackInfo"
    end
    add_enum "livekit.IngressState.Status" do
      value :ENDPOINT_INACTIVE, 0
      value :ENDPOINT_BUFFERING, 1
      value :ENDPOINT_PUBLISHING, 2
      value :ENDPOINT_ERROR, 3
    end
    add_message "livekit.InputVideoState" do
      optional :mime_type, :string, 1
      optional :width, :uint32, 3
      optional :height, :uint32, 4
      optional :framerate, :uint32, 5
    end
    add_message "livekit.InputAudioState" do
      optional :mime_type, :string, 1
      optional :channels, :uint32, 3
      optional :sample_rate, :uint32, 4
    end
    add_message "livekit.UpdateIngressRequest" do
      optional :ingress_id, :string, 1
      optional :name, :string, 2
      optional :room_name, :string, 3
      optional :participant_identity, :string, 4
      optional :participant_name, :string, 5
      optional :audio, :message, 6, "livekit.IngressAudioOptions"
      optional :video, :message, 7, "livekit.IngressVideoOptions"
    end
    add_message "livekit.ListIngressRequest" do
      optional :room_name, :string, 1
    end
    add_message "livekit.ListIngressResponse" do
      repeated :items, :message, 1, "livekit.IngressInfo"
    end
    add_message "livekit.DeleteIngressRequest" do
      optional :ingress_id, :string, 1
    end
    add_enum "livekit.IngressInput" do
      value :RTMP_INPUT, 0
    end
  end
end

module LiveKit
  module Proto
    CreateIngressRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("livekit.CreateIngressRequest").msgclass
    IngressAudioOptions = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("livekit.IngressAudioOptions").msgclass
    IngressVideoOptions = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("livekit.IngressVideoOptions").msgclass
    IngressInfo = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("livekit.IngressInfo").msgclass
    IngressState = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("livekit.IngressState").msgclass
    IngressState::Status = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("livekit.IngressState.Status").enummodule
    InputVideoState = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("livekit.InputVideoState").msgclass
    InputAudioState = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("livekit.InputAudioState").msgclass
    UpdateIngressRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("livekit.UpdateIngressRequest").msgclass
    ListIngressRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("livekit.ListIngressRequest").msgclass
    ListIngressResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("livekit.ListIngressResponse").msgclass
    DeleteIngressRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("livekit.DeleteIngressRequest").msgclass
    IngressInput = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("livekit.IngressInput").enummodule
  end
end
