# frozen_string_literal: true

# Generated by the protoc-gen-twirp_ruby gem v1.2.0. DO NOT EDIT!
# source: livekit_sip.proto

require "twirp"
require_relative "livekit_sip_pb"

module LiveKit
  module Proto
    class SIPService < ::Twirp::Service
      package "livekit"
      service "SIP"
      rpc :ListSIPTrunk, ListSIPTrunkRequest, ListSIPTrunkResponse, ruby_method: :list_sip_trunk
      rpc :CreateSIPInboundTrunk, CreateSIPInboundTrunkRequest, SIPInboundTrunkInfo, ruby_method: :create_sip_inbound_trunk
      rpc :CreateSIPOutboundTrunk, CreateSIPOutboundTrunkRequest, SIPOutboundTrunkInfo, ruby_method: :create_sip_outbound_trunk
      rpc :UpdateSIPInboundTrunk, UpdateSIPInboundTrunkRequest, SIPInboundTrunkInfo, ruby_method: :update_sip_inbound_trunk
      rpc :UpdateSIPOutboundTrunk, UpdateSIPOutboundTrunkRequest, SIPOutboundTrunkInfo, ruby_method: :update_sip_outbound_trunk
      rpc :GetSIPInboundTrunk, GetSIPInboundTrunkRequest, GetSIPInboundTrunkResponse, ruby_method: :get_sip_inbound_trunk
      rpc :GetSIPOutboundTrunk, GetSIPOutboundTrunkRequest, GetSIPOutboundTrunkResponse, ruby_method: :get_sip_outbound_trunk
      rpc :ListSIPInboundTrunk, ListSIPInboundTrunkRequest, ListSIPInboundTrunkResponse, ruby_method: :list_sip_inbound_trunk
      rpc :ListSIPOutboundTrunk, ListSIPOutboundTrunkRequest, ListSIPOutboundTrunkResponse, ruby_method: :list_sip_outbound_trunk
      rpc :DeleteSIPTrunk, DeleteSIPTrunkRequest, SIPTrunkInfo, ruby_method: :delete_sip_trunk
      rpc :CreateSIPDispatchRule, CreateSIPDispatchRuleRequest, SIPDispatchRuleInfo, ruby_method: :create_sip_dispatch_rule
      rpc :UpdateSIPDispatchRule, UpdateSIPDispatchRuleRequest, SIPDispatchRuleInfo, ruby_method: :update_sip_dispatch_rule
      rpc :ListSIPDispatchRule, ListSIPDispatchRuleRequest, ListSIPDispatchRuleResponse, ruby_method: :list_sip_dispatch_rule
      rpc :DeleteSIPDispatchRule, DeleteSIPDispatchRuleRequest, SIPDispatchRuleInfo, ruby_method: :delete_sip_dispatch_rule
      rpc :CreateSIPParticipant, CreateSIPParticipantRequest, SIPParticipantInfo, ruby_method: :create_sip_participant
      rpc :TransferSIPParticipant, TransferSIPParticipantRequest, ::Google::Protobuf::Empty, ruby_method: :transfer_sip_participant
    end

    class SIPClient < ::Twirp::Client
      client_for SIPService
    end
  end
end
