# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: livekit_connector_twilio.proto

require 'google/protobuf'

require 'livekit_agent_dispatch_pb'
require 'logger/options_pb'


descriptor_data = "\n\x1elivekit_connector_twilio.proto\x12\x07livekit\x1a\x1clivekit_agent_dispatch.proto\x1a\x14logger/options.proto\"\x8f\x05\n\x18\x43onnectTwilioCallRequest\x12T\n\x15twilio_call_direction\x18\x01 \x01(\x0e\x32\x35.livekit.ConnectTwilioCallRequest.TwilioCallDirection\x12\x11\n\troom_name\x18\x02 \x01(\t\x12*\n\x06\x61gents\x18\x03 \x03(\x0b\x32\x1a.livekit.RoomAgentDispatch\x12\x1c\n\x14participant_identity\x18\x04 \x01(\t\x12>\n\x10participant_name\x18\x05 \x01(\tB$\xb2P\x1e<redacted ({{ .Size }} bytes)>\xc0P\x01\x12\x42\n\x14participant_metadata\x18\x06 \x01(\tB$\xb2P\x1e<redacted ({{ .Size }} bytes)>\xc0P\x01\x12\x82\x01\n\x16participant_attributes\x18\x07 \x03(\x0b\x32<.livekit.ConnectTwilioCallRequest.ParticipantAttributesEntryB$\xb2P\x1e<redacted ({{ .Size }} bytes)>\xc0P\x01\x12\x1b\n\x13\x64\x65stination_country\x18\x08 \x01(\t\x1a<\n\x1aParticipantAttributesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\\\n\x13TwilioCallDirection\x12!\n\x1dTWILIO_CALL_DIRECTION_INBOUND\x10\x00\x12\"\n\x1eTWILIO_CALL_DIRECTION_OUTBOUND\x10\x01\"0\n\x19\x43onnectTwilioCallResponse\x12\x13\n\x0b\x63onnect_url\x18\x01 \x01(\tBFZ#github.com/livekit/protocol/livekit\xaa\x02\rLiveKit.Proto\xea\x02\x0eLiveKit::Protob\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module LiveKit
  module Proto
    ConnectTwilioCallRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("livekit.ConnectTwilioCallRequest").msgclass
    ConnectTwilioCallRequest::TwilioCallDirection = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("livekit.ConnectTwilioCallRequest.TwilioCallDirection").enummodule
    ConnectTwilioCallResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("livekit.ConnectTwilioCallResponse").msgclass
  end
end
