# frozen_string_literal: true

# Generated by the protoc-gen-twirp_ruby gem v1.2.0. DO NOT EDIT!
# source: livekit_egress.proto

require "twirp"
require_relative "livekit_egress_pb"

module LiveKit
  module Proto
    class EgressService < ::Twirp::Service
      package "livekit"
      service "Egress"
      rpc :StartRoomCompositeEgress, RoomCompositeEgressRequest, EgressInfo, ruby_method: :start_room_composite_egress
      rpc :StartWebEgress, WebEgressRequest, EgressInfo, ruby_method: :start_web_egress
      rpc :StartParticipantEgress, ParticipantEgressRequest, EgressInfo, ruby_method: :start_participant_egress
      rpc :StartTrackCompositeEgress, TrackCompositeEgressRequest, EgressInfo, ruby_method: :start_track_composite_egress
      rpc :StartTrackEgress, TrackEgressRequest, EgressInfo, ruby_method: :start_track_egress
      rpc :UpdateLayout, UpdateLayoutRequest, EgressInfo, ruby_method: :update_layout
      rpc :UpdateStream, UpdateStreamRequest, EgressInfo, ruby_method: :update_stream
      rpc :ListEgress, ListEgressRequest, ListEgressResponse, ruby_method: :list_egress
      rpc :StopEgress, StopEgressRequest, EgressInfo, ruby_method: :stop_egress
    end

    class EgressClient < ::Twirp::Client
      client_for EgressService
    end
  end
end
