# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: livekit_recording.proto

require 'google/protobuf/empty_pb'
require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("livekit_recording.proto", :syntax => :proto3) do
    add_message "livekit.StartRecordingRequest" do
      optional :options, :message, 6, "livekit.RecordingOptions"
      oneof :input do
        optional :url, :string, 1
        optional :template, :message, 2, "livekit.RecordingTemplate"
      end
      oneof :output do
        optional :s3_url, :string, 3
        optional :rtmp, :message, 4, "livekit.RtmpOutput"
        optional :file, :string, 5
      end
    end
    add_message "livekit.RecordingTemplate" do
      optional :layout, :string, 1
      oneof :room do
        optional :room_name, :string, 2
        optional :token, :string, 3
      end
    end
    add_message "livekit.RtmpOutput" do
      repeated :urls, :string, 1
    end
    add_message "livekit.RecordingOptions" do
      optional :preset, :enum, 1, "livekit.RecordingPreset"
      optional :width, :int32, 2
      optional :height, :int32, 3
      optional :depth, :int32, 4
      optional :framerate, :int32, 5
      optional :audio_bitrate, :int32, 6
      optional :audio_frequency, :int32, 7
      optional :video_bitrate, :int32, 8
    end
    add_message "livekit.StartRecordingResponse" do
      optional :recording_id, :string, 1
    end
    add_message "livekit.AddOutputRequest" do
      optional :recording_id, :string, 1
      optional :rtmp_url, :string, 2
    end
    add_message "livekit.RemoveOutputRequest" do
      optional :recording_id, :string, 1
      optional :rtmp_url, :string, 2
    end
    add_message "livekit.EndRecordingRequest" do
      optional :recording_id, :string, 1
    end
    add_enum "livekit.RecordingPreset" do
      value :NONE, 0
      value :HD_30, 1
      value :HD_60, 2
      value :FULL_HD_30, 3
      value :FULL_HD_60, 4
    end
  end
end

module Livekit
  module Proto
    StartRecordingRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("livekit.StartRecordingRequest").msgclass
    RecordingTemplate = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("livekit.RecordingTemplate").msgclass
    RtmpOutput = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("livekit.RtmpOutput").msgclass
    RecordingOptions = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("livekit.RecordingOptions").msgclass
    StartRecordingResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("livekit.StartRecordingResponse").msgclass
    AddOutputRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("livekit.AddOutputRequest").msgclass
    RemoveOutputRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("livekit.RemoveOutputRequest").msgclass
    EndRecordingRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("livekit.EndRecordingRequest").msgclass
    RecordingPreset = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("livekit.RecordingPreset").enummodule
  end
end
