# Code generated by protoc-gen-twirp_ruby 1.6.0, DO NOT EDIT.
require 'twirp'
require_relative 'livekit_recording_pb.rb'

module Livekit
  module Proto
    class RecordingServiceService < Twirp::Service
      package 'livekit'
      service 'RecordingService'
      rpc :StartRecording, StartRecordingRequest, RecordingResponse, :ruby_method => :start_recording
      rpc :EndRecording, EndRecordingRequest, RecordingResponse, :ruby_method => :end_recording
    end

    class RecordingServiceClient < Twirp::Client
      client_for RecordingServiceService
    end
  end
end
