# Code generated by protoc-gen-twirp_ruby 1.11.0, DO NOT EDIT.
require 'twirp'
require_relative 'livekit_agent_dispatch_pb.rb'

module LiveKit
  module Proto
    class AgentDispatchServiceService < ::Twirp::Service
      package 'livekit'
      service 'AgentDispatchService'
      rpc :CreateDispatch, CreateAgentDispatchRequest, AgentDispatch, :ruby_method => :create_dispatch
      rpc :DeleteDispatch, DeleteAgentDispatchRequest, AgentDispatch, :ruby_method => :delete_dispatch
      rpc :ListDispatch, ListAgentDispatchRequest, ListAgentDispatchResponse, :ruby_method => :list_dispatch
    end

    class AgentDispatchServiceClient < ::Twirp::Client
      client_for AgentDispatchServiceService
    end
  end
end
