# Code generated by protoc-gen-twirp_ruby 1.8.0, DO NOT EDIT.
require 'twirp'
require_relative 'livekit_recording_pb.rb'

module Livekit
  module Proto
    class RecordingServiceService < Twirp::Service
      package 'livekit'
      service 'RecordingService'
      rpc :StartRecording, StartRecordingRequest, StartRecordingResponse, :ruby_method => :start_recording
      rpc :AddOutput, AddOutputRequest, Google::Protobuf::Empty, :ruby_method => :add_output
      rpc :RemoveOutput, RemoveOutputRequest, Google::Protobuf::Empty, :ruby_method => :remove_output
      rpc :EndRecording, EndRecordingRequest, Google::Protobuf::Empty, :ruby_method => :end_recording
    end

    class RecordingServiceClient < Twirp::Client
      client_for RecordingServiceService
    end
  end
end
