# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: livekit_webhook.proto

require 'google/protobuf'

require 'livekit_models_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("livekit_webhook.proto", :syntax => :proto3) do
    add_message "livekit.WebhookEvent" do
      optional :event, :string, 1
      optional :room, :message, 2, "livekit.Room"
      optional :participant, :message, 3, "livekit.ParticipantInfo"
    end
  end
end

module Livekit
  WebhookEvent = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("livekit.WebhookEvent").msgclass
end
