# frozen_string_literal: true

# Generated by the protoc-gen-twirp_ruby gem v1.2.0. DO NOT EDIT!
# source: livekit_agent_dispatch.proto

require "twirp"
require_relative "livekit_agent_dispatch_pb"

module LiveKit
  module Proto
    class AgentDispatchService < ::Twirp::Service
      package "livekit"
      service "AgentDispatchService"
      rpc :CreateDispatch, CreateAgentDispatchRequest, AgentDispatch, ruby_method: :create_dispatch
      rpc :DeleteDispatch, DeleteAgentDispatchRequest, AgentDispatch, ruby_method: :delete_dispatch
      rpc :ListDispatch, ListAgentDispatchRequest, ListAgentDispatchResponse, ruby_method: :list_dispatch
    end

    class AgentDispatchClient < ::Twirp::Client
      client_for AgentDispatchService
    end
  end
end
